services:
  - type: web
    name: ipl-auction
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class=gthread --threads=4 --workers=1 --bind=0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
